[package]
name = "guessing_number"
version = "0.1.0"
authors = ["YinianDawn <dawn@yinian.tech>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
